/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CardapioSlugRouteImport } from './routes/cardapio.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioSlugRoute = CardapioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CardapioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cardapio': typeof CardapioRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cardapio': typeof CardapioRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cardapio': typeof CardapioRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/cardapio' | '/cliente' | '/cardapio/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/cardapio' | '/cliente' | '/cardapio/$slug'
  id: '__root__' | '/' | '/admin' | '/cardapio' | '/cliente' | '/cardapio/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CardapioRoute: typeof CardapioRouteWithChildren
  ClienteRoute: typeof ClienteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio/$slug': {
      id: '/cardapio/$slug'
      path: '/$slug'
      fullPath: '/cardapio/$slug'
      preLoaderRoute: typeof CardapioSlugRouteImport
      parentRoute: typeof CardapioRoute
    }
  }
}

interface CardapioRouteChildren {
  CardapioSlugRoute: typeof CardapioSlugRoute
}

const CardapioRouteChildren: CardapioRouteChildren = {
  CardapioSlugRoute: CardapioSlugRoute,
}

const CardapioRouteWithChildren = CardapioRoute._addFileChildren(
  CardapioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CardapioRoute: CardapioRouteWithChildren,
  ClienteRoute: ClienteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
